In [3]:
# Scaled Dot-Product Attention
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(42)

B, T, C = 2, 4, 2
x = torch.randn(B, T, C)
print(f"x[0]:\n {x[0]}")
query = nn.Linear(C, C)
key = nn.Linear(C, C)
value = nn.Linear(C, C)
tril = torch.tril(torch.ones(T, T))
q = query(x)
k = key(x)
v = value(x)
print(f"q[0]:\n {q[0]}")
print(f"v[0]:\n {v[0]}")

print("q @ k.transpose(1, 2)[0]")
print(q @ k.transpose(1, 2)[0])
attention_scores = (q @ k.transpose(1, 2)) / (k.shape[-1] ** 0.5)
print("attention_scores[0]")
print(attention_scores[0])
attention_scores = attention_scores.masked_fill(tril == 0, float("-inf"))
print("attention_scores[0]")
print(attention_scores[0])
atten_wei= F.softmax(attention_scores, dim=-1) 
print("atten_wei[0]")
print(atten_wei[0])
out = atten_wei @ v
print("out[0]")
print(out[0])


x[0]:
 tensor([[ 1.9269,  1.4873],
        [ 0.9007, -2.1055],
        [ 0.6784, -1.2345],
        [-0.0431, -1.6047]])
q[0]:
 tensor([[ 0.8800, -0.4509],
        [-0.0549, -0.7598],
        [-0.0850, -0.5294],
        [-0.5170, -0.3579]], grad_fn=<SelectBackward0>)
v[0]:
 tensor([[-0.3642,  0.4548],
        [ 2.0765,  1.9576],
        [ 1.4534,  1.2925],
        [ 1.6637,  1.0540]], grad_fn=<SelectBackward0>)
q @ k.transpose(1, 2)[0]
tensor([[[ 0.8466, -1.1636, -0.6758, -0.8822],
         [ 1.5116,  0.2629,  0.3584, -0.0411],
         [ 1.0558,  0.2508,  0.2953,  0.0153],
         [ 0.7393,  0.8340,  0.6470,  0.4423]],

        [[-0.8871,  0.7030,  0.3629,  0.5861],
         [ 0.4478,  1.0424,  0.7511,  0.6201],
         [-0.0689,  1.1157,  0.7377,  0.7411],
         [-0.5753,  0.8874,  0.5239,  0.6629]]], grad_fn=<UnsafeViewBackward0>)
attention_scores[0]
tensor([[ 0.5986, -0.8228, -0.4778, -0.6238],
        [ 1.0688,  0.1859,  0.2534, -0.0291],
        [ 0.7466,  0.1773,  0.2088,  0

In [4]:
# example for value weighted sum calculation
print(atten_wei[0,2:3,:]) 
print(v[0,:,:1])
print(atten_wei[0,2:3,:] @ v[0,:,:1])

tensor([[0.4651, 0.2632, 0.2716, 0.0000]], grad_fn=<SliceBackward0>)
tensor([[-0.3642],
        [ 2.0765],
        [ 1.4534],
        [ 1.6637]], grad_fn=<SliceBackward0>)
tensor([[0.7720]], grad_fn=<MmBackward0>)
